version: "3.8"
services:
  app:
    build: ./
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      - USER=user
    command: sh -c "cargo run"
    tty: true
    ports:
      - 2102:8080
