version: "3.8"
services:
  app:
    image: rust:latest
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      - USER=user
    command: sh -c "cargo run"
    tty: true
    ports:
      - 3300:8080
    environment:
      TZ: Asia/Tokyo
